name: Lint & Autoformat

on:
  push:
    branches: [ main, develop, "feature/**" ]

permissions:
  contents: write  # necesario para poder pushear

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # para poder commitear bien

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pylint

      - name: Autoformat with Black
        run: |
          black .
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(format): apply Black [skip ci]"
            git push
          fi

      - name: Flake8 (style)
        run: flake8 . --max-line-length=88 --ignore=E203,W503

      - name: Pylint
        run: pylint $(git ls-files '*.py')
